import { type CSSProperties } from '@mui/material';

export const DATE_FORMAT = 'DD-MM-YYYY';
export const YEAR_FIRST_DATE_FORMAT = 'YYYY-MM-DD';

export const DOT = '•';

export const formFloatingAnimation = {
    enter: (direction: 'forward' | 'backward') => ({
        x: direction === 'forward' ? 500 : -500,
    }),
    center: { x: 0, opacity: 1 },
    exit: (direction: 'forward' | 'backward') => ({
        x: direction === 'forward' ? -500 : 500,
    }),
};

export const ColumnBoxStyles: CSSProperties = {
    display: 'flex',
    flexDirection: 'column',
    gap: 2,
};

export const RowBoxStyles: CSSProperties = {
    display: 'flex',
    alignItems: 'center',
    gap: 1,
};

export const PaperStyles: CSSProperties = {
    ...ColumnBoxStyles,
    width: '100%',
    padding: 3,
    borderRadius: '14px',
};

export const SymptomsOptions = [
    { grouping: 'General', title: 'Fatigue' },
    { grouping: 'General', title: 'Weakness' },
    { grouping: 'General', title: 'Fever' },
    { grouping: 'General', title: 'Chills' },
    { grouping: 'General', title: 'Malaise (general feeling of illness)' },
    { grouping: 'General', title: 'Sweating' },
    { grouping: 'General', title: 'Weight gain' },
    { grouping: 'General', title: 'Weight loss' },

    { grouping: 'Head / Neurological', title: 'Headache' },
    { grouping: 'Head / Neurological', title: 'Migraine' },
    { grouping: 'Head / Neurological', title: 'Dizziness' },
    { grouping: 'Head / Neurological', title: 'Lightheadedness' },
    { grouping: 'Head / Neurological', title: 'Vertigo' },
    { grouping: 'Head / Neurological', title: 'Drowsiness' },
    { grouping: 'Head / Neurological', title: 'Insomnia' },
    { grouping: 'Head / Neurological', title: 'Confusion' },
    { grouping: 'Head / Neurological', title: 'Difficulty concentrating' },
    { grouping: 'Head / Neurological', title: 'Tremor' },
    { grouping: 'Head / Neurological', title: 'Tingling or numbness (paresthesia)' },

    { grouping: 'Gastrointestinal', title: 'Stomach pain' },
    { grouping: 'Gastrointestinal', title: 'Abdominal cramps' },
    { grouping: 'Gastrointestinal', title: 'Nausea' },
    { grouping: 'Gastrointestinal', title: 'Vomiting' },
    { grouping: 'Gastrointestinal', title: 'Diarrhea' },
    { grouping: 'Gastrointestinal', title: 'Constipation' },
    { grouping: 'Gastrointestinal', title: 'Bloating' },
    { grouping: 'Gastrointestinal', title: 'Gas' },
    { grouping: 'Gastrointestinal', title: 'Heartburn' },
    { grouping: 'Gastrointestinal', title: 'Loss of appetite' },
    { grouping: 'Gastrointestinal', title: 'Increased appetite' },
    { grouping: 'Gastrointestinal', title: 'Dry mouth' },

    { grouping: 'Cardiovascular', title: 'Palpitations' },
    { grouping: 'Cardiovascular', title: 'Rapid heart rate (tachycardia)' },
    { grouping: 'Cardiovascular', title: 'Slow heart rate (bradycardia)' },
    { grouping: 'Cardiovascular', title: 'Chest pain' },
    { grouping: 'Cardiovascular', title: 'Chest tightness' },
    { grouping: 'Cardiovascular', title: 'Low blood pressure symptoms' },
    { grouping: 'Cardiovascular', title: 'High blood pressure symptoms' },

    { grouping: 'Respiratory', title: 'Shortness of breath' },
    { grouping: 'Respiratory', title: 'Difficulty breathing' },
    { grouping: 'Respiratory', title: 'Cough' },
    { grouping: 'Respiratory', title: 'Wheezing' },
    { grouping: 'Respiratory', title: 'Chest congestion' },

    { grouping: 'Skin / Allergic Reactions', title: 'Rash' },
    { grouping: 'Skin / Allergic Reactions', title: 'Itching' },
    { grouping: 'Skin / Allergic Reactions', title: 'Hives' },
    { grouping: 'Skin / Allergic Reactions', title: 'Skin redness' },
    { grouping: 'Skin / Allergic Reactions', title: 'Swelling (face, lips, tongue)' },
    { grouping: 'Skin / Allergic Reactions', title: 'Dry skin' },
    { grouping: 'Skin / Allergic Reactions', title: 'Acne' },
    { grouping: 'Skin / Allergic Reactions', title: 'Sensitivity to sunlight' },

    { grouping: 'Musculoskeletal', title: 'Muscle pain' },
    { grouping: 'Musculoskeletal', title: 'Joint pain' },
    { grouping: 'Musculoskeletal', title: 'Muscle cramps' },
    { grouping: 'Musculoskeletal', title: 'Muscle weakness' },
    { grouping: 'Musculoskeletal', title: 'Back pain' },

    { grouping: 'Mental / Psychological', title: 'Anxiety' },
    { grouping: 'Mental / Psychological', title: 'Irritability' },
    { grouping: 'Mental / Psychological', title: 'Mood swings' },
    { grouping: 'Mental / Psychological', title: 'Depression' },
    { grouping: 'Mental / Psychological', title: 'Agitation' },
    { grouping: 'Mental / Psychological', title: 'Restlessness' },

    { grouping: 'Hormonal / Metabolic', title: 'Increased thirst' },
    { grouping: 'Hormonal / Metabolic', title: 'Frequent urination' },
    { grouping: 'Hormonal / Metabolic', title: 'Blood sugar changes' },
    { grouping: 'Hormonal / Metabolic', title: 'Fluid retention' },
    { grouping: 'Hormonal / Metabolic', title: 'Swelling in legs or hands' },

    { grouping: 'Vision / Sensory', title: 'Blurred vision' },
    { grouping: 'Vision / Sensory', title: 'Double vision' },
    { grouping: 'Vision / Sensory', title: 'Eye pain' },
    { grouping: 'Vision / Sensory', title: 'Dry eyes' },
    { grouping: 'Vision / Sensory', title: 'Ringing in ears (tinnitus)' },
    { grouping: 'Vision / Sensory', title: 'Hearing changes' },
    { grouping: 'Vision / Sensory', title: 'Altered taste' },
    { grouping: 'Vision / Sensory', title: 'Altered smell' },

    { grouping: '⚠️ Immediate Attention', title: 'Severe chest pain' },
    { grouping: '⚠️ Immediate Attention', title: 'Difficulty breathing' },
    {
        grouping: '⚠️ Immediate Attention',
        title: 'Severe allergic reaction (swelling of lips/face/tongue)',
    },
    { grouping: '⚠️ Immediate Attention', title: 'Fainting' },
    { grouping: '⚠️ Immediate Attention', title: 'Severe dizziness' },
    { grouping: '⚠️ Immediate Attention', title: 'Uncontrolled vomiting' },
] as const;

export const Symptoms = [
    'Fatigue',
    'Weakness',
    'Fever',
    'Chills',
    'Malaise (general feeling of illness)',
    'Sweating',
    'Weight gain',
    'Weight loss',
    'Head / Neurological',
    'Headache',
    'Migraine',
    'Dizziness',
    'Lightheadedness',
    'Vertigo',
    'Drowsiness',
    'Insomnia',
    'Confusion',
    'Difficulty concentrating',
    'Tremor',
    'Tingling or numbness (paresthesia)',
    'Gastrointestinal',
    'Stomach pain',
    'Abdominal cramps',
    'Nausea',
    'Vomiting',
    'Diarrhea',
    'Constipation',
    'Bloating',
    'Gas',
    'Heartburn',
    'Loss of appetite',
    'Increased appetite',
    'Dry mouth',
    'Cardiovascular',
    'Palpitations',
    'Rapid heart rate (tachycardia)',
    'Slow heart rate (bradycardia)',
    'Chest pain',
    'Chest tightness',
    'Low blood pressure symptoms',
    'High blood pressure symptoms',
    'Respiratory',
    'Shortness of breath',
    'Difficulty breathing',
    'Cough',
    'Wheezing',
    'Chest congestion',
    'Skin / Allergic Reactions',
    'Rash',
    'Itching',
    'Hives',
    'Skin redness',
    'Swelling (face, lips, tongue)',
    'Dry skin',
    'Acne',
    'Sensitivity to sunlight',
    'Musculoskeletal',
    'Muscle pain',
    'Joint pain',
    'Muscle cramps',
    'Muscle weakness',
    'Back pain',
    'Mental / Psychological',
    'Anxiety',
    'Irritability',
    'Mood swings',
    'Depression',
    'Agitation',
    'Restlessness',
    'Hormonal / Metabolic',
    'Increased thirst',
    'Frequent urination',
    'Blood sugar changes',
    'Fluid retention',
    'Swelling in legs or hands',
    'Vision / Sensory',
    'Blurred vision',
    'Double vision',
    'Eye pain',
    'Dry eyes',
    'Ringing in ears (tinnitus)',
    'Hearing changes',
    'Altered taste',
    'Altered smell',
    '(These are useful to highlight in the UI)',
    'Severe chest pain',
    'Severe allergic reaction (swelling of lips/face/tongue)',
    'Fainting',
    'Severe dizziness',
    'Uncontrolled vomiting',
] as const;
